# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/rias/projects/chatrn

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/rias/projects/chatrn

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rias/projects/chatrn/CMakeFiles /home/rias/projects/chatrn//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rias/projects/chatrn/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named chatrn

# Build rule for target.
chatrn: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 chatrn
.PHONY : chatrn

# fast build rule for target.
chatrn/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chatrn.dir/build.make CMakeFiles/chatrn.dir/build
.PHONY : chatrn/fast

chatsession.o: chatsession.c.o
.PHONY : chatsession.o

# target to build an object file
chatsession.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chatrn.dir/build.make CMakeFiles/chatrn.dir/chatsession.c.o
.PHONY : chatsession.c.o

chatsession.i: chatsession.c.i
.PHONY : chatsession.i

# target to preprocess a source file
chatsession.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chatrn.dir/build.make CMakeFiles/chatrn.dir/chatsession.c.i
.PHONY : chatsession.c.i

chatsession.s: chatsession.c.s
.PHONY : chatsession.s

# target to generate assembly for a file
chatsession.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chatrn.dir/build.make CMakeFiles/chatrn.dir/chatsession.c.s
.PHONY : chatsession.c.s

client.o: client.c.o
.PHONY : client.o

# target to build an object file
client.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chatrn.dir/build.make CMakeFiles/chatrn.dir/client.c.o
.PHONY : client.c.o

client.i: client.c.i
.PHONY : client.i

# target to preprocess a source file
client.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chatrn.dir/build.make CMakeFiles/chatrn.dir/client.c.i
.PHONY : client.c.i

client.s: client.c.s
.PHONY : client.s

# target to generate assembly for a file
client.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chatrn.dir/build.make CMakeFiles/chatrn.dir/client.c.s
.PHONY : client.c.s

config.o: config.c.o
.PHONY : config.o

# target to build an object file
config.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chatrn.dir/build.make CMakeFiles/chatrn.dir/config.c.o
.PHONY : config.c.o

config.i: config.c.i
.PHONY : config.i

# target to preprocess a source file
config.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chatrn.dir/build.make CMakeFiles/chatrn.dir/config.c.i
.PHONY : config.c.i

config.s: config.c.s
.PHONY : config.s

# target to generate assembly for a file
config.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chatrn.dir/build.make CMakeFiles/chatrn.dir/config.c.s
.PHONY : config.c.s

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chatrn.dir/build.make CMakeFiles/chatrn.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chatrn.dir/build.make CMakeFiles/chatrn.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chatrn.dir/build.make CMakeFiles/chatrn.dir/main.c.s
.PHONY : main.c.s

server.o: server.c.o
.PHONY : server.o

# target to build an object file
server.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chatrn.dir/build.make CMakeFiles/chatrn.dir/server.c.o
.PHONY : server.c.o

server.i: server.c.i
.PHONY : server.i

# target to preprocess a source file
server.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chatrn.dir/build.make CMakeFiles/chatrn.dir/server.c.i
.PHONY : server.c.i

server.s: server.c.s
.PHONY : server.s

# target to generate assembly for a file
server.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chatrn.dir/build.make CMakeFiles/chatrn.dir/server.c.s
.PHONY : server.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... chatrn"
	@echo "... chatsession.o"
	@echo "... chatsession.i"
	@echo "... chatsession.s"
	@echo "... client.o"
	@echo "... client.i"
	@echo "... client.s"
	@echo "... config.o"
	@echo "... config.i"
	@echo "... config.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... server.o"
	@echo "... server.i"
	@echo "... server.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

